#!/usr/bin/env ruby
# encoding: utf-8
# Usage: wlt scaffold <type>
# Summary: Initialize a web log today instance.
# Help: Initialize an empty directory with a full or basic functionnal example.
#
# wlt scaffold basic
#     minimal scaffolding
# wlt scaffold full
#     full featured scaffolding

require 'fileutils'

type = ARGV[0]

if Dir.glob("**/*").count > 0
  puts "Must be run in an empty folder."
  exit
end

if type.nil?
  puts "You must select a scaffold, full or basic."
  exit
end

scaffolddir = File.join(File.dirname(__FILE__), '..', 'share', 'wlt', 'scaffolding', type, '.')
unless Dir.exists? scaffolddir
  puts "You must select a scaffold, full or basic."
  exit
end

FileUtils.cp_r scaffolddir, '.'
puts "Don't forget to edit config.yaml"
