#!/usr/bin/env ruby
# Usage: wlt build
# Summary: Clean and build site
# Help: This will clean the _site directory
# and generate all content inside it.

$LOAD_PATH.unshift(File.join(File.dirname(__FILE__),'..', *%w[lib]))

require "wlt.rb"

wlt = Wlt.new
wlt.init
wlt.css
wlt.js
wlt.pub
