#!/usr/bin/env ruby
# encoding: utf-8
# Usage: wlt assets
# Summary: Build assets.
# Help: This will build the assets (js, css, pub)

$LOAD_PATH.unshift(File.join(File.dirname(__FILE__),'..', *%w[lib]))

require "wlt.rb"
require 'logging'
Logging.logger.formatter = proc do |severity, datetime, progname, msg|
  "#{msg}\n"
end

wlt = Wlt.new
wlt.css
wlt.js
wlt.pub
