#!/usr/bin/env ruby
# encoding: utf-8
# Usage: wlt build
# Summary: Clean and build site
# Help: This will clean the _site directory
# and generate all content inside it.

$LOAD_PATH.unshift(File.join(File.dirname(__FILE__),'..', *%w[lib]))

require "wlt.rb"
require 'logging'
Logging.logger.formatter = proc do |severity, datetime, progname, msg|
  "#{msg}\n"
end

wlt = Wlt.new
wlt.generate
