#!/usr/bin/env ruby
# encoding: utf-8
# Usage: wlt serve [all]
# Summary: Serve after build
# Help: Serve compiled version on http://localhost:4000
#
# You can pass an "all" flag to generate all content,
# without reading the published state.

require 'serve'
require 'serve/application'

$LOAD_PATH.unshift(File.join(File.dirname(__FILE__),'..', *%w[lib]))

require "wlt.rb"
require 'logging'
Logging.logger.formatter = proc do |severity, datetime, progname, msg|
  "#{msg}\n"
end

all = ARGV[0] == "all"


wlt = Wlt.new true
wlt.generate all

Serve::Application.run ["_site"]
